- hosts: monitor
  become: True
  roles:
    - william-yeh.prometheus

  vars:
    prometheus_components: [ "prometheus", "alertmanager", "node_exporter" ]
    prometheus_alertmanager_hostport: "localhost:9093"
    prometheus_use_systemd: True
    prometheus_use_service: False
    prometheus_conf_main: prometheus.yml


- hosts:
    - master
    - replicas
  become: True
  roles:
    - william-yeh.prometheus

  vars:
    prometheus_components: [ "node_exporter" ]
    prometheus_use_systemd: True
    prometheus_use_service: False
  